'use client';

import { useState } from 'react';
import { motion } from 'framer-motion';
import { GlassPanel } from './GlassPanel';
import { ChromeButton } from './ChromeButton';

interface ReadmeGeneratorProps {
  username: string;
  stats: {
    totalRepos: number;
    totalStars: number;
    totalCommits: number;
    followers: number;
  };
  personality: {
    type: string;
    badge: string;
    icon: string;
  };
}

const THEMES = [
  { id: 'cyberpunk', name: 'Cyberpunk', colors: ['#00ffff', '#ff00ff'] },
  { id: 'sunset', name: 'Sunset Vibes', colors: ['#ff6b6b', '#ffd93d'] },
  { id: 'forest', name: 'Forest', colors: ['#00ff88', '#00ffff'] },
  { id: 'ocean', name: 'Ocean', colors: ['#0066ff', '#00ffff'] },
  { id: 'purple', name: 'Purple Haze', colors: ['#ff00ff', '#00ff88'] },
];

export function ReadmeGenerator({ username, stats, personality }: ReadmeGeneratorProps) {
  const [copied, setCopied] = useState(false);
  const [selectedTheme, setSelectedTheme] = useState('cyberpunk');
  const [copiedImage, setCopiedImage] = useState(false);

  const domain = process.env.NEXT_PUBLIC_DOMAIN || 'https://gitwrapped.vercel.app';
  const cardUrl = `${domain}/api/card?username=${username}&theme=${selectedTheme}`;

  const markdown = `
![GitWrapped](${cardUrl})

---

### 📊 My GitHub Stats

| Metric | Value |
|--------|-------|
| 📚 Repositories | ${stats.totalRepos} |
| ⭐ Total Stars | ${stats.totalStars} |
| 🎯 Total Commits | ${stats.totalCommits} |
| 👥 Followers | ${stats.followers} |

---

### 🏆 Achievements

- **Dev Type**: ${personality.type}
- **Badge**: ${personality.icon} ${personality.badge}

---
> Generated by [GitWrapped](https://gitwrapped.vercel.app) ✨
  `.trim();

  const copyToClipboard = async () => {
    await navigator.clipboard.writeText(markdown);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const copyImageUrl = async () => {
    await navigator.clipboard.writeText(cardUrl);
    setCopiedImage(true);
    setTimeout(() => setCopiedImage(false), 2000);
  };

  const downloadImage = async () => {
    try {
      const response = await fetch(cardUrl);
      const svg = await response.text();
      const blob = new Blob([svg], { type: 'image/svg+xml' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `gitwrapped-${username}-${selectedTheme}.svg`;
      a.click();
      URL.revokeObjectURL(url);
    } catch (error) {
      console.error('Failed to download image:', error);
    }
  };

  const shareToTwitter = () => {
    const text = encodeURIComponent(
      `Check out my GitWrapped! 🔥\n\n📚 ${stats.totalRepos} repos\n⭐ ${stats.totalStars} stars\n🎯 ${stats.totalCommits} commits\n\nGenerate yours at gitwrapped.vercel.app #GitWrapped #Developer`
    );
    window.open(`https://twitter.com/intent/tweet?text=${text}`, '_blank');
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5, delay: 0.6 }}
    >
      <GlassPanel glowColor="pink" className="p-8">
        <h3 className="font-orbitron text-2xl font-bold text-white mb-6">🧾 README Generator</h3>

        {/* Theme selector */}
        <div className="mb-6">
          <span className="font-mono text-sm text-gray-400 block mb-3">Choose Theme:</span>
          <div className="flex flex-wrap gap-3">
            {THEMES.map((theme) => (
              <button
                key={theme.id}
                onClick={() => setSelectedTheme(theme.id)}
                className={`px-4 py-2 rounded-lg font-mono text-sm transition-all ${
                  selectedTheme === theme.id
                    ? 'ring-2 ring-white'
                    : 'opacity-60 hover:opacity-100'
                }`}
                style={{
                  background: `linear-gradient(135deg, ${theme.colors[0]}30, ${theme.colors[1]}30)`,
                  border: `1px solid ${selectedTheme === theme.id ? '#fff' : theme.colors[0]}`,
                }}
              >
                <div className="flex items-center gap-2">
                  <div 
                    className="w-3 h-3 rounded-full"
                    style={{ background: theme.colors[0] }}
                  />
                  <div 
                    className="w-3 h-3 rounded-full"
                    style={{ background: theme.colors[1] }}
                  />
                  <span className="text-white">{theme.name}</span>
                </div>
              </button>
            ))}
          </div>
        </div>

        {/* Preview Card */}
        <div className="mb-6 p-4 bg-[rgba(0,0,0,0.3)] rounded-lg overflow-hidden">
          <img
            src={cardUrl}
            alt="GitWrapped Card"
            className="w-full max-w-md mx-auto rounded-lg"
          />
        </div>

        {/* Actions */}
        <div className="flex flex-wrap gap-4 mb-4">
          <ChromeButton onClick={copyToClipboard} glowColor="cyan">
            {copied ? '✓ Copied!' : '📋 Copy Markdown'}
          </ChromeButton>
          <ChromeButton onClick={copyImageUrl} glowColor="blue">
            {copiedImage ? '✓ Copied!' : '🔗 Copy Image URL'}
          </ChromeButton>
          <ChromeButton onClick={downloadImage} glowColor="magenta">
            💾 Download Image
          </ChromeButton>
        </div>

        {/* Social Share */}
        <div className="flex flex-wrap gap-4 pt-4 border-t border-[rgba(255,255,255,0.1)]">
          <button
            onClick={shareToTwitter}
            className="flex items-center gap-2 px-4 py-2 rounded-lg bg-[rgba(29,161,242,0.1)] hover:bg-[rgba(29,161,242,0.2)] transition-colors text-[#1DA1F2] font-mono text-sm"
          >
            <svg className="w-4 h-4" fill="currentColor" viewBox="0 0 24 24">
              <path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z"/>
            </svg>
            Share on X
          </button>
        </div>

        {/* Markdown Preview */}
        <details className="mt-6">
          <summary className="font-mono text-sm text-gray-400 cursor-pointer hover:text-white">
            View Markdown Code
          </summary>
          <pre className="mt-4 p-4 bg-[rgba(0,0,0,0.5)] rounded-lg overflow-x-auto text-xs font-mono text-gray-300 max-h-60">
            {markdown}
          </pre>
        </details>
      </GlassPanel>
    </motion.div>
  );
}
